### ISSUE TITLE
No output when running vswhere in a container in Kubernetes

### ISSUE THREAD

**Issue by keiransteele** [microsoft/vswhere#212]
I'm building Windows build agent container that we would like to run in Kubernetes. I have been able to build the container and use it to run jobs when running with plain docker but when I push the container to an Azure registry and then run it as a statefulset in AKS, vswhere produces no output when run, it won't even output the header and copyright info.

This is the Dockerfile and as noted, it will successfully run one of our build pipelines. The task that fails is the "Visual Studio Build" task which runs vswhere to determine the installed versions of Visual Studio.

```Dockerfile
# escape=`

# Use the latest Windows Server Core image with .NET Framework 4.8.
FROM mcr.microsoft.com/dotnet/framework/sdk:4.8-20200211-windowsservercore-ltsc2019

# Restore the default Windows shell for correct batch processing.
SHELL ["cmd", "/S", "/C"]

# Download the Build Tools bootstrapper.
ADD https://aka.ms/vs/16/release/vs_buildtools.exe C:\TEMP\vs_buildtools.exe

# Install Build Tools excluding workloads and components with known issues.
RUN C:\TEMP\vs_buildtools.exe --quiet --wait --norestart --nocache `
  --installPath C:\BuildTools `
  --all `
  --remove Microsoft.VisualStudio.Component.Windows10SDK.10240 `
  --remove Microsoft.VisualStudio.Component.Windows10SDK.10586 `
  --remove Microsoft.VisualStudio.Component.Windows10SDK.14393 `
  --remove Microsoft.VisualStudio.Component.Windows81SDK `
  || IF "%ERRORLEVEL%"=="3010" EXIT 0

# Add Jetbrains Dotcover executable for code coverage testing.
RUN mkdir "c:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/Common7/IDE/CommonExtensions/Microsoft/TestWindow"
COPY [ "TestWindow", "c:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/Common7/IDE/CommonExtensions/Microsoft/TestWindow" ]
COPY dotcover C:\TEMP\dotcover

# # Install Chocolatey and install Java for Sonarqube
RUN powershell.exe Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1')); choco install -y openjdk11redhatbuild

WORKDIR /azp

COPY start.ps1 .

CMD powershell .\start.ps1
```

This is the start.ps1 file which enables the container to join Azure Devops as an agent. It is from a Microsoft documentation page.

```powershell
if (-not (Test-Path Env:AZP_URL)) {
  Write-Error "error: missing AZP_URL environment variable"
  exit 1
}

if (-not (Test-Path Env:AZP_TOKEN_FILE)) {
  if (-not (Test-Path Env:AZP_TOKEN)) {
    Write-Error "error: missing AZP_TOKEN environment variable"
    exit 1
  }

  $Env:AZP_TOKEN_FILE = "\azp\.token"
  $Env:AZP_TOKEN | Out-File -FilePath $Env:AZP_TOKEN_FILE
}

Remove-Item Env:AZP_TOKEN

if ($Env:AZP_WORK -and -not (Test-Path Env:AZP_WORK)) {
  New-Item $Env:AZP_WORK -ItemType directory | Out-Null
}

New-Item "\azp\agent" -ItemType directory | Out-Null

# Let the agent ignore the token env variables
$Env:VSO_AGENT_IGNORE = "AZP_TOKEN,AZP_TOKEN_FILE"

Set-Location agent

Write-Host "1. Determining matching Azure Pipelines agent..." -ForegroundColor Cyan

$base64AuthInfo = [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes(":$(Get-Content ${Env:AZP_TOKEN_FILE})"))
$package = Invoke-RestMethod -Headers @{Authorization = ("Basic $base64AuthInfo") } "$(${Env:AZP_URL})/_apis/distributedtask/packages/agent?platform=win-x64&`$top=1"
Write-Host $package
$packageUrl = $package[0].Value.downloadUrl

Write-Host $packageUrl

Write-Host "2. Downloading and installing Azure Pipelines agent..." -ForegroundColor Cyan

$wc = New-Object System.Net.WebClient
$wc.DownloadFile($packageUrl, "$(Get-Location)\agent.zip")

Expand-Archive -Path "agent.zip" -DestinationPath "\azp\agent"

try {
  Write-Host "3. Configuring Azure Pipelines agent..." -ForegroundColor Cyan

  .\config.cmd --unattended `
    --agent "$(if (Test-Path Env:AZP_AGENT_NAME) { ${Env:AZP_AGENT_NAME} } else { ${Env:computername} })" `
    --url "$(${Env:AZP_URL})" `
    --auth PAT `
    --token "$(Get-Content ${Env:AZP_TOKEN_FILE})" `
    --pool "$(if (Test-Path Env:AZP_POOL) { ${Env:AZP_POOL} } else { 'Default' })" `
    --work "$(if (Test-Path Env:AZP_WORK) { ${Env:AZP_WORK} } else { '_work' })" `
    --replace

  # remove the administrative token before accepting work
  Remove-Item $Env:AZP_TOKEN_FILE

  Write-Host "4. Running Azure Pipelines agent..." -ForegroundColor Cyan

  .\run.cmd
}
finally {
  Write-Host "Cleanup. Removing Azure Pipelines agent..." -ForegroundColor Cyan

  .\config.cmd remove --unattended `
    --auth PAT `
    --token "$(Get-Content ${Env:AZP_TOKEN_FILE})"
}
```

To run the container locally you just need to:

1. Build it: ```docker build -t windowsagent:latest .```
2. Run it:  ```docker run -e AZP_TOKEN=<Insert PAT here> -e AZP_AGENT_NAME=win-docker-test -e AZP_URL=https://xxxx.visualstudio.com -e AZP_POOL=windows-docker-test windowsagent:latest```

To run the container and test the failure in AKS, you need an AKS cluster with a Windows node pool and somewhere to push the container to.

This is my statefulset yaml file.

```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: adoagentwin
  labels:
    app: adoagent
    adoagentos: windows
spec:
  ports:
    - port: 80
      name: web
  clusterIP: None
  selector:
    app: adoagent
    adoagentos: windows
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: adoagentwin
  labels:
    app: adoagent
    adoagentos: windows
spec:
  selector:
    matchLabels:
      app: adoagent
      adoagentos: windows
  serviceName: adoagentwin
  replicas: 1
  template:
    metadata:
      labels:
        app: adoagent
        adoagentos: windows
    spec:
      terminationGracePeriodSeconds: 20
      containers:
        - name: adoagent
          image: 
          imagePullPolicy: Always
          env:
            - name: AZP_TOKEN
              value:
            - name: AZP_URL
              value:
            - name: AZP_POOL
              value: windows-kubernetes-test
          ports:
            - containerPort: 80
              name: web
          resources:
            requests:
              memory: 4Gi
            limits:
              memory: 8Gi
      nodeSelector:
        beta.kubernetes.io/instance-type: Standard_F8s_v2
        beta.kubernetes.io/os: windows
```

I have also raised a premiere support case to see if they can help.
